# --- Database Connection ---
spring.datasource.url=jdbc:postgresql://localhost:5432/velocell_db
spring.datasource.username=postgres
spring.datasource.password=overclocked

# --- Hibernate / JPA Settings ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- gRPC Server Port ---
grpc.server.port=9090